// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// T_fun
double T_fun(double Tc, double Y_T, double DHa, double DSd, double DHd);
RcppExport SEXP _xylomod_T_fun(SEXP TcSEXP, SEXP Y_TSEXP, SEXP DHaSEXP, SEXP DSdSEXP, SEXP DHdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type Tc(TcSEXP);
    Rcpp::traits::input_parameter< double >::type Y_T(Y_TSEXP);
    Rcpp::traits::input_parameter< double >::type DHa(DHaSEXP);
    Rcpp::traits::input_parameter< double >::type DSd(DSdSEXP);
    Rcpp::traits::input_parameter< double >::type DHd(DHdSEXP);
    rcpp_result_gen = Rcpp::wrap(T_fun(Tc, Y_T, DHa, DSd, DHd));
    return rcpp_result_gen;
END_RCPP
}
// expand
DataFrame expand(DataFrame data, double phi0, double pi0, double CRD0, double Y_P, double Y_T, double h, double s);
RcppExport SEXP _xylomod_expand(SEXP dataSEXP, SEXP phi0SEXP, SEXP pi0SEXP, SEXP CRD0SEXP, SEXP Y_PSEXP, SEXP Y_TSEXP, SEXP hSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< double >::type pi0(pi0SEXP);
    Rcpp::traits::input_parameter< double >::type CRD0(CRD0SEXP);
    Rcpp::traits::input_parameter< double >::type Y_P(Y_PSEXP);
    Rcpp::traits::input_parameter< double >::type Y_T(Y_TSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(expand(data, phi0, pi0, CRD0, Y_P, Y_T, h, s));
    return rcpp_result_gen;
END_RCPP
}
// expand_ring
List expand_ring(List ring, DataFrame data, double Y_P, double Y_T, double h, double s);
RcppExport SEXP _xylomod_expand_ring(SEXP ringSEXP, SEXP dataSEXP, SEXP Y_PSEXP, SEXP Y_TSEXP, SEXP hSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type ring(ringSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type Y_P(Y_PSEXP);
    Rcpp::traits::input_parameter< double >::type Y_T(Y_TSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(expand_ring(ring, data, Y_P, Y_T, h, s));
    return rcpp_result_gen;
END_RCPP
}
// divide
DataFrame divide(DataFrame data, double Nc, double phi0, double pi0, double Y_P, double Y_T);
RcppExport SEXP _xylomod_divide(SEXP dataSEXP, SEXP NcSEXP, SEXP phi0SEXP, SEXP pi0SEXP, SEXP Y_PSEXP, SEXP Y_TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type Nc(NcSEXP);
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< double >::type pi0(pi0SEXP);
    Rcpp::traits::input_parameter< double >::type Y_P(Y_PSEXP);
    Rcpp::traits::input_parameter< double >::type Y_T(Y_TSEXP);
    rcpp_result_gen = Rcpp::wrap(divide(data, Nc, phi0, pi0, Y_P, Y_T));
    return rcpp_result_gen;
END_RCPP
}
// grow_ring
List grow_ring(List ring, DataFrame data, double Nc, double phi0, double pi0, double CRD0, double Y_P, double Y_T, double h, double s);
RcppExport SEXP _xylomod_grow_ring(SEXP ringSEXP, SEXP dataSEXP, SEXP NcSEXP, SEXP phi0SEXP, SEXP pi0SEXP, SEXP CRD0SEXP, SEXP Y_PSEXP, SEXP Y_TSEXP, SEXP hSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type ring(ringSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    Rcpp::traits::input_parameter< double >::type Nc(NcSEXP);
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< double >::type pi0(pi0SEXP);
    Rcpp::traits::input_parameter< double >::type CRD0(CRD0SEXP);
    Rcpp::traits::input_parameter< double >::type Y_P(Y_PSEXP);
    Rcpp::traits::input_parameter< double >::type Y_T(Y_TSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(grow_ring(ring, data, Nc, phi0, pi0, CRD0, Y_P, Y_T, h, s));
    return rcpp_result_gen;
END_RCPP
}
// initialize_ring
List initialize_ring(DateVector formation_date, bool cell_wise, bool historic, double phi0, double pi0, double CRD0);
RcppExport SEXP _xylomod_initialize_ring(SEXP formation_dateSEXP, SEXP cell_wiseSEXP, SEXP historicSEXP, SEXP phi0SEXP, SEXP pi0SEXP, SEXP CRD0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DateVector >::type formation_date(formation_dateSEXP);
    Rcpp::traits::input_parameter< bool >::type cell_wise(cell_wiseSEXP);
    Rcpp::traits::input_parameter< bool >::type historic(historicSEXP);
    Rcpp::traits::input_parameter< double >::type phi0(phi0SEXP);
    Rcpp::traits::input_parameter< double >::type pi0(pi0SEXP);
    Rcpp::traits::input_parameter< double >::type CRD0(CRD0SEXP);
    rcpp_result_gen = Rcpp::wrap(initialize_ring(formation_date, cell_wise, historic, phi0, pi0, CRD0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_xylomod_T_fun", (DL_FUNC) &_xylomod_T_fun, 5},
    {"_xylomod_expand", (DL_FUNC) &_xylomod_expand, 8},
    {"_xylomod_expand_ring", (DL_FUNC) &_xylomod_expand_ring, 6},
    {"_xylomod_divide", (DL_FUNC) &_xylomod_divide, 6},
    {"_xylomod_grow_ring", (DL_FUNC) &_xylomod_grow_ring, 10},
    {"_xylomod_initialize_ring", (DL_FUNC) &_xylomod_initialize_ring, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_xylomod(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
