# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

T_fun <- function(Tc, Y_T = 8, DHa = 87.5e3, DSd = 1.09e3, DHd = 333e3) {
    .Call(`_xylomod_T_fun`, Tc, Y_T, DHa, DSd, DHd)
}

wall_thickness <- function(WA, CRD, CTD) {
    .Call(`_xylomod_wall_thickness`, WA, CRD, CTD)
}

expand <- function(data, phi0 = 0.13, pi0 = -0.8, CRD0 = 8.3, Y_P = 0.05, Y_T = 5, h = 0.043*1.8, s = 1.8) {
    .Call(`_xylomod_expand`, data, phi0, pi0, CRD0, Y_P, Y_T, h, s)
}

expand_ring <- function(ring, data, Y_P = 0.05, Y_T = 5, h = 0.043*1.8, s = 1.8) {
    .Call(`_xylomod_expand_ring`, ring, data, Y_P, Y_T, h, s)
}

divide <- function(data, Nc = 8.85, phi0 = 0.13, pi0 = -0.8, Y_P = 0.05, Y_T = 5) {
    .Call(`_xylomod_divide`, data, Nc, phi0, pi0, Y_P, Y_T)
}

grow_ring <- function(ring, data, Nc = 8.85, phi0 = 0.13, pi0 = -0.8, CRD0 = 8.3, Y_P = 0.05, Y_T = 8, h = 0.043*1.8, s = 1.8) {
    .Call(`_xylomod_grow_ring`, ring, data, Nc, phi0, pi0, CRD0, Y_P, Y_T, h, s)
}

initialize_ring <- function(formation_date = NA_integer_, cell_wise = FALSE, historic = FALSE, phi0 = 0.13, pi0 = -0.8, CRD0 = 8.3) {
    .Call(`_xylomod_initialize_ring`, formation_date, cell_wise, historic, phi0, pi0, CRD0)
}

