# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

temp_fun <- function(Tc, Y_T = 5, DHa = 87.5e3, DSd = 1.09e3, DHd = 333e3) {
    .Call(`_xylomod_temp_fun`, Tc, Y_T, DHa, DSd, DHd)
}

r_fun <- function(psi, Tc, pi, phi, Y_P, Y_T) {
    .Call(`_xylomod_r_fun`, psi, Tc, pi, phi, Y_P, Y_T)
}

expansion <- function(psi, Tc, start = 1L, phi0 = 0.13, pi0 = -0.8, CRD0 = 8.3, Y_P = 0.05, Y_T = 5, h = 0.043*1.8, s = 1.8) {
    .Call(`_xylomod_expansion`, psi, Tc, start, phi0, pi0, CRD0, Y_P, Y_T, h, s)
}

expansion_seq <- function(psi, Tc, start_vec, phi0 = 0.13, pi0 = -0.8, CRD0 = 8.3, Y_P = 0.05, Y_T = 5, h = 0.043*1.8, s = 1.8) {
    .Call(`_xylomod_expansion_seq`, psi, Tc, start_vec, phi0, pi0, CRD0, Y_P, Y_T, h, s)
}

division <- function(psi, Tc, Nc = 8.85, phi = 0.13, pi = -0.8, Y_P = 0.05, Y_T = 5) {
    .Call(`_xylomod_division`, psi, Tc, Nc, phi, pi, Y_P, Y_T)
}

